version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=czh888888
      - TZ=Asia/Shanghai
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - cnetwork


  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - cnetwork
    volumes:
      - ./redis-data:/data

  rabbitmq:
    image: rabbitmq:3.12.6-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: linbei
      RABBITMQ_DEFAULT_PASS: 888888
    networks:
      - cnetwork

  nacos:
    image: nacos/nacos-server:v2.2.0-slim
    container_name: nacos
    restart: always
    ports:
      - "8848:8848"
    volumes:
      - ./nacos-data:/home/nacos/data
    networks:
      - cnetwork
    environment:
      - MODE=standalone
      - PREFER_HOST_MODE=hostname
      - TZ=Asia/Shanghai
      - JVM_XMS=256M
      - JVM_XMX=256M


  sentinel:
    image: bladex/sentinel-dashboard:1.8.5
    container_name: sentinel
    ports:
      - "8858:8858"
    restart: always
    networks:
      - cnetwork
    environment:
      - AUTH_USERNAME=sentinel
      - AUTH_PASSWORD=888888
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      - nacos


  elasticsearch:
    image: elasticsearch:7.8.1
    container_name: elasticsearch
    restart: always
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
    volumes:
      - es-data:/usr/share/elasticsearch/data
      - es-plugins:/usr/share/elasticsearch/plugins
    privileged: true
    networks:
      - cnetwork
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: kibana:7.8.1
    container_name: kibana
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTIC_PASSWORD=888888
    networks:
      - cnetwork
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  es-data:
  es-plugins:

networks:
  cnetwork:

